name: rsna_2024

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  # Basics
  - python
  - pip
  
  # Jupyterlab
  - ipykernel >= 6.29.4
  
  # Stats
  - numpy == 1.26.4   # pin version for wandb
  - pandas >= 2.2.2
  - scipy >= 1.14.0
  
  # Plots
  - matplotlib >= 3.8.4
  - seaborn >= 0.13.2
  - plotly >= 5.22.0
  - ipywidgets >= 8.1.3
  
  # Misc
  - tqdm >= 4.66.4
  - wandb >= 0.16.5
  - kaggle >= 1.6.14
  - pyarrow >= 16.1.0
  - grad-cam >= 1.5.2
  
  # ML
  - scikit-learn >= 1.5.0
  - scikit-image >= 0.24.0
  - albumentations >= 1.4.1
  
  # DL
  - pytorch >= 2.3.1
  - torchvision >= 0.18.1
  - pytorch-cuda = 12.1
  - timm >= 1.0.7

  # MRI
  - pydicom >= 2.4.4
