name: rsna_2024
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  # Basics
  - python >= 3.11.4
  - pip >= 23.1.2
  
  # Jupyterlab
  - ipykernel >= 6.29.4
  
  # Stats
  - numpy >= 1.24.3
  - pandas >= 1.5.3
  - scipy >= 1.10.1
  
  # Plots
  - matplotlib >= 3.7.1
  - seaborn >= 0.12.2
  - plotly >= 5.15.0
  - ipywidgets >= 8.0.4
  
  # Misc
  - tqdm >= 4.65.0
  - wandb >= 0.15.8
  - kaggle >= 1.5.16
  
  # ML
  - scikit-learn >= 1.3.0
  - scikit-image >= 0.20.0
  - albumentations >= 1.4.0
  
  # DL
  - pytorch >= 2.1.0
  - torchvision >= 0.16.0
  - pytorch-cuda = 11.8
  - timm >= 0.9.8

  # MRI
  - pydicom >= 2.4.4
 
  - pip:    
    # Misc
    - pyarrow >= 12.0.1
    - grad-cam >= 1.5.0
    - braindecode >= 0.8.1
